# Generated by Django 5.1 on 2024-10-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_details',
            options={'verbose_name': 'Order detail', 'verbose_name_plural': 'Order details'},
        ),
    ]
