# Generated by Django 5.1 on 2024-10-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_details_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_details',
            options={},
        ),
    ]
